name: Python package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      id: setupy
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pipenv'
        cache-dependency-path:
          Pipfile.lock
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install octave
        python -m pip install --upgrade pip
        pip install pipenv

    - name: install pipenv
      if: ${{steps.setupy.outputs.cache-hit != 'true'}}
      run: |
        pipenv install --dev --deploy
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv run pytest --doctest-modules
